#!/usr/bin/python3
import sys

def tonum(s):   #def 
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
        ans += tonum(line) #intは文字列を整数に
    
print(ans)
